import pandas as pd
from datetime import datetime, timezone

CSV_PATH = "data/world_economic.csv"
CHANGELOG_PATH = "CHANGELOG.md"
META_COLS = {"iso3", "country", "region", "income_group", "capital", "latitude", "longitude", "year"}

df = pd.read_csv(CSV_PATH)
num_cols = [c for c in df.columns if c not in META_COLS]
n_indicators = len(num_cols)
null_pct = df[num_cols].isna().mean().mean() * 100 if num_cols else 0
today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

# Indicateurs avec le moins de couverture (signal de qualité)
coverage = df[num_cols].notna().mean().sort_values().head(3)
weakest = ", ".join(f"{c} ({v*100:.0f}%)" for c, v in coverage.items())

entry = f"""
## {today}
- Coverage: {df['country'].nunique()} countries, {df['year'].min()}–{df['year'].max()}, {n_indicators} indicators
- Overall null rate: {null_pct:.1f}%
- Lowest coverage: {weakest}
- Auto-generated by monthly GitHub Actions pipeline.
"""

with open(CHANGELOG_PATH, "r", encoding="utf-8") as f:
    content = f.read()

with open(CHANGELOG_PATH, "w", encoding="utf-8") as f:
    f.write(content.replace("<!-- AUTO-GENERATED -->", f"<!-- AUTO-GENERATED -->{entry}", 1))

print(f"✓ Changelog entry added for {today}")