"""
Power BI Measures Exporter
Generates measures.dax from core/investment.py and core/analytics.py
Keeps Power BI model synchronized with Streamlit app logic.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


def generate_measures_dax() -> str:
    """Generate the DAX measures file content."""
    # Read actual weights from core/investment.py
    from core.investment import INVESTMENT_INDICATORS
    from core.constants import INVERSE_INDICATORS
    
    # Build weights table for DAX
    weights_lines = []
    for ind, weight in INVESTMENT_INDICATORS.items():
        weights_lines.append(f'                {{"{ind}", {weight}}},')
    weights_table = "\n".join(weights_lines).rstrip(",")
    
    # Template with interpolated weights
    dax_template = f'''// ============================================================================
// GLOBAL ECONOMIC INTELLIGENCE DASHBOARD - POWER BI MEASURES
// AUTO-GENERATED by scripts/export_pbi_measures.py
// Source: core/investment.py (weights), core/analytics.py (normalization)
// ============================================================================

// --------------------------------------------------------------------------
// 1. BASE MEASURES
// --------------------------------------------------------------------------
Base_Value = SELECTEDVALUE(Fact_EconomicIndicators[value])
Base_Avg_Value = AVERAGE(Fact_EconomicIndicators[value])

// --------------------------------------------------------------------------
// 2. MIN-MAX NORMALIZATION (world-level)
// --------------------------------------------------------------------------
_World_Min = CALCULATE(MIN(Fact_EconomicIndicators[value]), REMOVEFILTERS(Dim_Country))
_World_Max = CALCULATE(MAX(Fact_EconomicIndicators[value]), REMOVEFILTERS(Dim_Country))

_Normalized_Value = 
    VAR val = [Base_Value]
    VAR w_min = [_World_Min]
    VAR w_max = [_World_Max]
    VAR range_val = w_max - w_min
    RETURN IF(ISBLANK(val) || range_val = 0, BLANK(), DIVIDE(val - w_min, range_val, 0))

_Normalized_Adjusted = 
    VAR norm = [_Normalized_Value]
    VAR is_inverse = SELECTEDVALUE(Dim_Indicator[is_inverse], FALSE())
    RETURN IF(ISBLANK(norm), BLANK(), IF(is_inverse, 1 - norm, norm))

// --------------------------------------------------------------------------
// 3. PESTEL PILLAR SCORES (0-100)
// --------------------------------------------------------------------------
PESTEL_Pillar_Score = 
    VAR pillar_values = ADDCOLUMNS(VALUES(Dim_Indicator[indicator_id]), "@norm_adj", [_Normalized_Adjusted])
    VAR valid_values = FILTER(pillar_values, NOT ISBLANK([@norm_adj]))
    RETURN IF(COUNTROWS(valid_values) > 0, MEDIANX(valid_values, [@norm_adj]) * 100, BLANK())

// --------------------------------------------------------------------------
// 4. INVESTMENT SCORE (0-100) - Weights from core/investment.py
// --------------------------------------------------------------------------
Investment_Score = 
    VAR weights = 
        DATATABLE(
            "indicator_id", STRING,
            "weight", DOUBLE,
            {{
{weights_table}
            }}
        )
    VAR score_components =
        ADDCOLUMNS(
            weights,
            "@norm_adj", 
                CALCULATE([_Normalized_Adjusted], Dim_Indicator[indicator_id] = EARLIER([indicator_id]))
        )
    VAR valid_components = FILTER(score_components, NOT ISBLANK([@norm_adj]))
    VAR total_weight = SUMX(valid_components, [weight])
    VAR weighted_sum = SUMX(valid_components, [@norm_adj] * [weight])
    RETURN IF(total_weight > 0, DIVIDE(weighted_sum, total_weight, 0) * 100, BLANK())

// --------------------------------------------------------------------------
// 5. CAGR / TCAM
// --------------------------------------------------------------------------
CAGR = 
    VAR min_year = MIN(Dim_Time[year])
    VAR max_year = MAX(Dim_Time[year])
    VAR n_years = max_year - min_year
    VAR first_val = CALCULATE([Base_Avg_Value], Dim_Time[year] = min_year)
    VAR last_val = CALCULATE([Base_Avg_Value], Dim_Time[year] = max_year)
    RETURN IF(n_years > 0 && first_val > 0 && last_val > 0, POWER(DIVIDE(last_val, first_val), 1 / n_years) - 1, BLANK())

CAGR_Pct = IF(ISBLANK([CAGR]), BLANK(), [CAGR] * 100)

// --------------------------------------------------------------------------
// 6. RED FLAGS (from core/investment.py thresholds)
// --------------------------------------------------------------------------
_Red_Flag_Inflation = IF(CALCULATE([Base_Avg_Value], Dim_Indicator[indicator_id] = "inflation_cpi_pct") > 10, 1, 0)
_Red_Flag_Debt = IF(CALCULATE([Base_Avg_Value], Dim_Indicator[indicator_id] = "debt_pct_gdp") > 70, 1, 0)
_Red_Flag_Unemployment = IF(CALCULATE([Base_Avg_Value], Dim_Indicator[indicator_id] = "unemployment_pct") > 15, 1, 0)
_Red_Flag_Current_Account = IF(CALCULATE([Base_Avg_Value], Dim_Indicator[indicator_id] = "current_account_pct_gdp") < -5, 1, 0)

Red_Flags_Total = [_Red_Flag_Inflation] + [_Red_Flag_Debt] + [_Red_Flag_Unemployment] + [_Red_Flag_Current_Account]
Has_Red_Flags = IF([Red_Flags_Total] > 0, "🔴", "✅")

// --------------------------------------------------------------------------
// 7. RISK/REWARD MATRIX
// --------------------------------------------------------------------------
Risk_Metric = 
    VAR inflation_values = CALCULATETABLE(VALUES(Fact_EconomicIndicators[value]), Dim_Indicator[indicator_id] = "inflation_cpi_pct")
    VAR mean_inf = AVERAGEX(inflation_values, Fact_EconomicIndicators[value])
    VAR std_inf = STDEVX.P(inflation_values, Fact_EconomicIndicators[value])
    RETURN IF(ISBLANK(mean_inf), BLANK(), mean_inf + COALESCE(std_inf, 0))

Quadrant_Classification = 
    VAR cagr = [CAGR_Pct]
    VAR risk = [Risk_Metric]
    VAR med_cagr = CALCULATE(MEDIANX(VALUES(Dim_Country[iso3]), [CAGR_Pct]), REMOVEFILTERS(Dim_Country))
    VAR med_risk = CALCULATE(MEDIANX(VALUES(Dim_Country[iso3]), [Risk_Metric]), REMOVEFILTERS(Dim_Country))
    RETURN SWITCH(TRUE(),
        ISBLANK(cagr) || ISBLANK(risk), "N/A",
        cagr >= med_cagr && risk <= med_risk, "⭐ Star",
        cagr >= med_cagr && risk > med_risk, "❓ Question Mark",
        cagr < med_cagr && risk <= med_risk, "💰 Cash Cow",
        "⚠️ Dog")

// --------------------------------------------------------------------------
// 8. OPPORTUNITIES RANKING
// --------------------------------------------------------------------------
Is_Top_Opportunity = IF([Red_Flags_Total] = 0 && NOT ISBLANK([Investment_Score]), 1, 0)

Opportunity_Rank = 
    IF([Is_Top_Opportunity] = 1,
        RANKX(FILTER(ALL(Dim_Country), [Is_Top_Opportunity] = 1), [Investment_Score], , DESC, Dense),
        BLANK())

// --------------------------------------------------------------------------
// 9. UTILITIES
// --------------------------------------------------------------------------
Score_Category = 
    VAR score = [Investment_Score]
    RETURN SWITCH(TRUE(),
        ISBLANK(score), "N/A",
        score >= 70, "Very Attractive",
        score >= 50, "Intermediate",
        "Fragile")

Selected_Year_Label = 
    VAR y = SELECTEDVALUE(Dim_Time[year])
    RETURN IF(ISBLANK(y), "All Years", "Year " & y)

Country_Count = DISTINCTCOUNT(Dim_Country[iso3])
Indicator_Count = DISTINCTCOUNT(Dim_Indicator[indicator_id])
'''
    return dax_template


def main():
    print("=" * 60)
    print("Power BI Measures Exporter")
    print("=" * 60)
    
    output_path = Path(__file__).parent.parent / "data" / "powerbi" / "measures.dax"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    dax_content = generate_measures_dax()
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(dax_content)
    
    print(f"✓ Generated {output_path}")
    print(f"  Size: {output_path.stat().st_size / 1024:.1f} KB")
    print(f"  Measures: {dax_content.count(' = ')} definitions")
    
    print("\nNext steps in Power BI Desktop:")
    print("1. Open Power BI Desktop → External Tools → Tabular Editor")
    print("2. Right-click on Tables → New Measure for each block")
    print("3. Or use the Advanced Scripting window to paste all measures at once")
    print("=" * 60)


if __name__ == "__main__":
    main()