[theme]
base = "light"
primaryColor = "#0067C0"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[server]
enableStaticServing = true
headless = false
runOnSave = true

[runner]
fastReruns = true
magicEnabled = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
